# Generated by Django 2.2.4 on 2020-03-23 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('city', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=500)),
                ('day', models.CharField(max_length=500)),
                ('hour', models.CharField(max_length=500)),
                ('main_image', models.ImageField(upload_to='image_product')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image_product')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image_product')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
