# Generated by Django 2.2.4 on 2020-04-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200409_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='city',
            field=models.CharField(max_length=500, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='events',
            name='day',
            field=models.CharField(max_length=500, verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='events',
            name='details',
            field=models.TextField(verbose_name='detalhes'),
        ),
        migrations.AlterField(
            model_name='events',
            name='district',
            field=models.CharField(max_length=500, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='events',
            name='hour',
            field=models.CharField(max_length=500, verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Imagem não obrigatória. ', null=True, upload_to='image_event', verbose_name='imagem 2'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Imagem não obrigatória. ', null=True, upload_to='image_event', verbose_name='imagem 3'),
        ),
        migrations.AlterField(
            model_name='events',
            name='main_image',
            field=models.ImageField(upload_to='image_event', verbose_name='imagem principal'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=500, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='events',
            name='street',
            field=models.CharField(max_length=500, verbose_name='rua'),
        ),
    ]
