# Generated by Django 2.2.4 on 2020-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_our'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='street',
            field=models.CharField(help_text='Nome da rua e o número da habitação', max_length=500, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='Imagem'),
        ),
    ]
